mod board_component;
mod card_component;
mod character;
mod component;
mod component_id;
pub mod helper_clickable;
pub mod helper_macroquad;
mod label_component;
mod text_drawer;
mod types;
mod value_bar_component;
mod value_bar_item_component;
mod value_component;

pub use board_component::BoardComponent;
pub use card_component::CardComponent;
pub use character::*;
pub use component::Component;
use component_id::ComponentId;
use helper_clickable::ClickableResult;
pub use label_component::LabelComponent;
pub use text_drawer::TextDrawer;
pub use types::UpdateResult;
pub use value_bar_component::ValueBarComponent;
pub use value_bar_item_component::ValueBarItemComponent;
pub use value_component::ValueComponent;
